### ISSUE TITLE
Enki crashes after putting a whitespace

### ISSUE THREAD

**Issue by agoodfellow123** [andreikop/enki#476]
Here I am again, sorry for making too many issues but I really want to use enki. This time I got this:
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/qutepart/__init__.py", line 1287, in paintEvent
    self._drawIndentMarkersAndEdge(event.rect())
  File "/usr/lib/python3.10/site-packages/qutepart/__init__.py", line 1279, in _drawIndentMarkersAndEdge
    drawWhiteSpace(block, column, text[column])
  File "/usr/lib/python3.10/site-packages/qutepart/__init__.py", line 1198, in drawWhiteSpace
    painter.drawRect(QRect(xPos, middleHeight, 2, 2))
TypeError: arguments did not match any overloaded call:
  QRect(): too many arguments
  QRect(int, int, int, int): argument 1 has unexpected type 'float'
  QRect(QPoint, QPoint): argument 1 has unexpected type 'float'
  QRect(QPoint, QSize): argument 1 has unexpected type 'float'
  QRect(QRect): argument 1 has unexpected type 'float'
```
Once again I checked all the lines in the error message and compared my files with the qutepart git, they all seem to be the same.

**Comment by andreikop** [comment]
Thank you for the report!
I've fixed this bug in `qutepart`, and 2 more places which might crash because of this error.

**Comment by abitrolly** [comment]
Still getting this error on Fedora 36. Looks like the patch was not released https://packages.fedoraproject.org/pkgs/python-qutepart/python3-qutepart/fedora-36.html

**Comment by andreikop** [comment]
@raphgro, I've released Qutepart 3.3.3
Could you update it in Fedora?

**Comment by abitrolly** [comment]
Fixed https://release-monitoring.org/project/7977/ entry, and https://bugzilla.redhat.com/show_bug.cgi?id=2117236 is created automatically.

**Comment by andreikop** [comment]
Amazing. I hope Enki also will be updated.
Sent email to Raphael

**Comment by rapgro** [comment]
See Fedora Upstream Monitoring 
https://bugzilla.redhat.com/show_bug.cgi?id=2117246
https://bugzilla.redhat.com/show_bug.cgi?id=2117236

@abitrolly For what Fedora release(s) do you need a new build? Okay, I'm going to rebuild for F36.

@andreikop FWIW my nick here is @rapgro. Thanks for your e-mail, otherwise I'd have properly not noticed.

**Comment by abitrolly** [comment]
@rapgro fixed Enki release for F36 would be awesome.

**Comment by rapgro** [comment]
New builds are available.
Fedora 36 https://bodhi.fedoraproject.org/updates/FEDORA-2022-8cf9d64c36
Fedora 35 https://bodhi.fedoraproject.org/updates/FEDORA-2022-3cd4e699ca

**Comment by abitrolly** [comment]
@rapgro can't test them. Is there some switch that needs to be clicked to get the update from "pending" to "testing"?

**Comment by abitrolly** [comment]
Fedora update works. Thanks. )
